# Generated by Django 4.2.1 on 2023-10-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=200)),
            ],
        ),
    ]
